# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: darkzeros/freedomdb:0.0.2
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: Building Debug
          command: |
            cmake -H. -Bdebug -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON
            cmake --build debug -- -j
      - store_artifacts:
          path: debug/freedomdb-tool

      - run:
          name: Building Release
          command: |
            cmake -H. -Brelease -DCMAKE_BUILD_TYPE=Release
            cmake --build release -- -j
      - store_artifacts:
          path: release/freedomdb-tool

      - run:
          name: Building Python
          command: sudo python3 ./setup.py install

      - run:
          name: Native tests
          command: |
            mkdir -p catch-results
            sudo service postgresql start
            ./debug/native-tests -r junit -o catch-results/junit.xml
      - store_test_results:
          path: catch-results
      - store_artifacts:
          path: catch-results

      - run:
          name: Python tests
          command: python3 -m pytest tests --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
