# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  python: circleci/python@1.3.2

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Installing TOOLs
          command: |
            sudo apt-get update
            sudo apt-get install -y gcc g++ build-essential cmake 
            sudo apt-get install -y python3 python3-pip python3-distutils
            sudo apt-get install -y libpython3-dev libboost-dev libpq-dev libpqxx-dev ninja-build
            pip install pytest
      - run:
          name: Prepare submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Building Debug
          command: |
            cmake -H. -Bdebug -DCMAKE_BUILD_TYPE=Debug
            cmake --build debug -- -j16
      - store_artifacts:
          path: debug/*.so
      - store_artifacts:
          path: debug/freedomdb-tool
      - run:
          name: Building Release
          command: |
            cmake -H. -Brelease -DCMAKE_BUILD_TYPE=Release
            cmake --build debug -- -j16
      - store_artifacts:
          path: release/*.so
      - store_artifacts:
          path: release/freedomdb-tool
      - run:
          name: Native tests
          command: |
            ./debug/native-tests
      - run:
          name: Python tests
          command: |
            python -m pytest tests
