# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Installing TOOLs
          command: 'sudo apt-get update && sudo apt-get install -y gcc g++ build-essential cmake libpython3-dev libboost-dev libpq-dev libpqxx-dev ninja-build'
      - run:
          name: Prepare submodules
          command: 'git submodule update --init --recursive'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Building
          command: 'cmake --build build'
      - run:
          name: Native tests
          command: './build/native-tests'
      - run:
          name: Python tests
          command: 'pytest tests'
