# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Installing TOOLs
          command: 'sudo apt-get update && apt-get install -y gcc g++ build-essentials cmake libpython-dev libboost-dev libpq-dev libpqxx-dev ninja-build'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'

